PATCH http://localhost:8080/api/v1/admin/members/3834/badges
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzM4NCJ9.eyJhdXRob3JpdHkiOiJST0xFX0FETUlOIiwiZW1haWwiOiJ3b2R5ZHRuc0BuYXZlci5jb20iLCJzdWIiOiJ3b2R5ZHRuc0BuYXZlci5jb20iLCJpYXQiOjE2ODgxNzQ1NDQsImV4cCI6MTY4ODE3NjM0NH0.uc8lIluehvNUgiFt4dEWGzqoQ2F8suvptyJxLDdZmPetlBWUE_tBQPKX72GNrzbu

{
  "badges": [
    "POST_FIVE_REVIEWS"
  ]
}
