spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    open-in-view: true

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: ${H2_URL}
    username: ${H2_USERNAME}
    password:

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${ORGANIZATION_EMAIL_ADDRESS}
    password: ${ORGANIZATION_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      org.hibernate.SQLQuery: debug

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: ${ACCESS_TOKEN_EXPIRATION_MINUTES}
  refresh-token-expiration-minutes: ${REFRESH_TOKEN_EXPIRATION_MINUTES}
