spring:
 datasource:
  
  #url: jdbc:oracle:thin:@onboard_medium?TNS_ADMIN=[전자지갑주소]
  username: APTC_USER
  password: Onboard!side7
  driver-class-name:  oracle.jdbc.OracleDriver
  # hikari library load 시 사용자를 찾지 못함 
  #hikari:
    #connection-timeout: 3000
    #validation-timeout: 3000
    #schema: self 
    #maximum-pool-size: 20
    #idle-timeout: 200000
    #max-lifetime: 240000
    #pool-name: oraPool
    
 jpa:
  hibernate:
   ddl-auto: none
  properties:
   hibernate:
    format_sql:true
   database-platform: org.hibernate.dialect.Oracle12cDialect
    
 mvc:
    static-path-pattern: /static/**   
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
logging:
  level:
    root: info

server:
  port: 8080
